//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNET_TrainerClient.UNET_Server_Reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UNET_Server_Reference.IService1", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLargeObject", ReplyAction="http://tempuri.org/IService1/GetLargeObjectResponse")]
        System.IO.Stream GetLargeObject(string _filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLargeObject", ReplyAction="http://tempuri.org/IService1/GetLargeObjectResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetLargeObjectAsync(string _filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAvailableFiles", ReplyAction="http://tempuri.org/IService1/GetAvailableFilesResponse")]
        string[] GetAvailableFiles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAvailableFiles", ReplyAction="http://tempuri.org/IService1/GetAvailableFilesResponse")]
        System.Threading.Tasks.Task<string[]> GetAvailableFilesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTestRoles", ReplyAction="http://tempuri.org/IService1/GetTestRolesResponse")]
        string[] GetTestRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTestRoles", ReplyAction="http://tempuri.org/IService1/GetTestRolesResponse")]
        System.Threading.Tasks.Task<string[]> GetTestRolesAsync();
        
        // CODEGEN: Generating message contract since the operation SaveLargeObject is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveLargeObject", ReplyAction="http://tempuri.org/IService1/SaveLargeObjectResponse")]
        UNET_TrainerClient.UNET_Server_Reference.SaveLargeObjectResponse SaveLargeObject(UNET_TrainerClient.UNET_Server_Reference.SaveFileInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveLargeObject", ReplyAction="http://tempuri.org/IService1/SaveLargeObjectResponse")]
        System.Threading.Tasks.Task<UNET_TrainerClient.UNET_Server_Reference.SaveLargeObjectResponse> SaveLargeObjectAsync(UNET_TrainerClient.UNET_Server_Reference.SaveFileInfo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveFileInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveFileInfo {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long Length;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string MimeType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public SaveFileInfo() {
        }
        
        public SaveFileInfo(string FileName, long Length, string MimeType, System.IO.Stream FileByteStream) {
            this.FileName = FileName;
            this.Length = Length;
            this.MimeType = MimeType;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveLargeObjectResponse {
        
        public SaveLargeObjectResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : UNET_TrainerClient.UNET_Server_Reference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<UNET_TrainerClient.UNET_Server_Reference.IService1>, UNET_TrainerClient.UNET_Server_Reference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream GetLargeObject(string _filename) {
            return base.Channel.GetLargeObject(_filename);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetLargeObjectAsync(string _filename) {
            return base.Channel.GetLargeObjectAsync(_filename);
        }
        
        public string[] GetAvailableFiles() {
            return base.Channel.GetAvailableFiles();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAvailableFilesAsync() {
            return base.Channel.GetAvailableFilesAsync();
        }
        
        public string[] GetTestRoles() {
            return base.Channel.GetTestRoles();
        }
        
        public System.Threading.Tasks.Task<string[]> GetTestRolesAsync() {
            return base.Channel.GetTestRolesAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UNET_TrainerClient.UNET_Server_Reference.SaveLargeObjectResponse UNET_TrainerClient.UNET_Server_Reference.IService1.SaveLargeObject(UNET_TrainerClient.UNET_Server_Reference.SaveFileInfo request) {
            return base.Channel.SaveLargeObject(request);
        }
        
        public void SaveLargeObject(string FileName, long Length, string MimeType, System.IO.Stream FileByteStream) {
            UNET_TrainerClient.UNET_Server_Reference.SaveFileInfo inValue = new UNET_TrainerClient.UNET_Server_Reference.SaveFileInfo();
            inValue.FileName = FileName;
            inValue.Length = Length;
            inValue.MimeType = MimeType;
            inValue.FileByteStream = FileByteStream;
            UNET_TrainerClient.UNET_Server_Reference.SaveLargeObjectResponse retVal = ((UNET_TrainerClient.UNET_Server_Reference.IService1)(this)).SaveLargeObject(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UNET_TrainerClient.UNET_Server_Reference.SaveLargeObjectResponse> UNET_TrainerClient.UNET_Server_Reference.IService1.SaveLargeObjectAsync(UNET_TrainerClient.UNET_Server_Reference.SaveFileInfo request) {
            return base.Channel.SaveLargeObjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<UNET_TrainerClient.UNET_Server_Reference.SaveLargeObjectResponse> SaveLargeObjectAsync(string FileName, long Length, string MimeType, System.IO.Stream FileByteStream) {
            UNET_TrainerClient.UNET_Server_Reference.SaveFileInfo inValue = new UNET_TrainerClient.UNET_Server_Reference.SaveFileInfo();
            inValue.FileName = FileName;
            inValue.Length = Length;
            inValue.MimeType = MimeType;
            inValue.FileByteStream = FileByteStream;
            return ((UNET_TrainerClient.UNET_Server_Reference.IService1)(this)).SaveLargeObjectAsync(inValue);
        }
    }
}
